// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    ImageContainer: typeof import('./src/components/Picture/ImageContainer.vue')['default']
    ImageRender: typeof import('./src/components/Picture/ImageRender.vue')['default']
  }
}
