// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    ImageContainer: typeof import('./src/components/Picture/ImageContainer.vue')['default']
    ImageRender: typeof import('./src/components/Picture/ImageRender.vue')['default']
  }
}
